### ISSUE TITLE
index.d.ts and snackbar.d.ts files missing (v1.1.2)

### ISSUE THREAD

**Issue by marcbuils** [bradmartin/nativescript-snackbar#10]
Hi,

For information, the files index.d.ts and snackbar.d.ts are missing on NPM for the version 1.1.2
(https://registry.npmjs.org/nativescript-snackbar/-/nativescript-snackbar-1.1.2.tgz).

**Comment by bradmartin** [comment]
Dang. Should just be index.d.ts now. I forgot to update the ignore. I'll republish soon

**Comment by bradmartin** [comment]
published and should have `index.d.ts` pulled down now and working. Let me know if still an issue. Feel free to close this if it works @marcbuils thanks for reporting :+1:

**Comment by marcbuils** [comment]
I just try it, the v1.1.3 is ok ;)
Thanks !
