### ISSUE TITLE
Unable to build for iOS via AppBuilder

### ISSUE THREAD

**Issue by felixkrautschuk** [bradmartin/nativescript-snackbar#11]
Hi,

the snackbar-plugin works fantastic on Android, but unfortunately I am not able to build the NativeScript app for iOS via Telerik AppBuilder.

I get the following message:

> Cannot build project because module nativescript-snackbar contains insecure code. Remove the module and try again.

Here is the complete build-log:

> ios Build Tooling revision 2016.08.05.3r
>     Build Tooling Hostname administrators-mac-7.local
>     Warning: npm
>     Warning: WARN
>     Warning: package.json @ No description
>     Warning: npm
>     Warning: WARN
>     Warning: package.json
>     Warning: @ No repository field.
>     Warning: npm
>     Warning: WARN package.json @ No README data
>     Warning: npm
>     Warning: WARN
>     Warning: package.json
>     Warning: @ No license field.
>     Error: Cannot build project because module nativescript-snackbar contains insecure code. Remove the module and try again.
>     Error: 'Build failed with error code 2'

I use the following configuration:
- NativeScript 2.1.0
- tns-core-modules 2.1.0
- nativescript-snackbar 1.1.3
- Telerik AppBuilder 3.4.1-724

Please tell me if you have any hints that can help me. I hope it is not something AppBuilder-specific...

Thank you in advance and best regards.

**Comment by bradmartin** [comment]
That's an issue with AppBuilder. I'll have to contact the Telerik AppBuilder team and have them whitelist the new contributors to the plugin. All authors/contributors for plugins via AppBuilder must be whitelisted for security purposes with AppBuilder. Pinging them now. Thanks.

**Comment by matt4446** [comment]
who can we pester to speed it up ? ;-)

Oddly enough the android version works in appbuilder. It is just the IOS version that doesn't.

**Comment by bradmartin** [comment]
Yea I forget the specifics with app builder. Think it also has something to
do with the cocoapod. I'll try reaching out again to them

**Comment by matt4446** [comment]
Thanks Brad!
By the way these _all work_ fine (build at least) with appbuilder: 

```
"nativescript-cardview": "~1.1.7",
"nativescript-floatingactionbutton": "~2.2.4",
"nativescript-pulltorefresh": "~1.1.4"
```

Ever need a tester for appbuilder give me a message.

**Comment by bradmartin** [comment]
Is this working on AppBuilder yet? If not, I'll bug the telerik team again.

**Comment by felixkrautschuk** [comment]
Hi brad, thanks for asking.
Unfortunately there has nothing changed yet :/
Still getting the error message, that the module contains 'insecure code'.

**Comment by bradmartin** [comment]
Response from team: _we are working on improvements in this area and with our next release (at the second part of September), you'll no longer see this error ("insecure code")_

**Comment by felixkrautschuk** [comment]
Thanks for your help ;)

**Comment by bradmartin** [comment]
@seppel1992 I'm assuming this is good now that the last release was published.

**Comment by felixkrautschuk** [comment]
@bradmartin Sorry, I forgot to mention it here... yes, the plugin works fine on both platforms since the latest AppBuilder update :) Thanks again for your commitment!
