### ISSUE TITLE
Make snackbar work in a nativescript-angular application

### ISSUE THREAD

**Issue by magar91** [bradmartin/nativescript-snackbar#13]
I've been trying to use tha snackbar in a nativescript with angular application but can't seem to make it work with angular 2, is it possible to use it with angular 2?

**Comment by bradmartin** [comment]
I think I've seen someone use this with angular native. It's compatible by default because it doesn't assume angular is involved. I'll ping a few guys who will know for sure

**Comment by bradmartin** [comment]
@triniwiz @roblav96 either of you used snackbar in NS+NG to confirm it works without issue?

**Comment by triniwiz** [comment]
@bradmartin no

**Comment by roblav96** [comment]
@bradmartin I've been using the plugin with a `core` build so I wouldn't know. I can check tho.

**Comment by bradmartin** [comment]
I see no reason it wouldn't work so just curious if there's any issue

**Comment by greenstevester** [comment]
also tried in ns-angular and got:
 _SnackBar error: ReferenceError: Can't find variable: SSSnackbar

**Comment by bradmartin** [comment]
SSSnackbar would be the iOS pod. Any errors during your build? Also what
version of cocoapods do you have installed?

**Comment by greenstevester** [comment]
No errors during the build, but while running:

CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:342:26: Unhandled Promise rejection: Can't find variable: SSSnackbar ; Zone: angular ; Task: Promise.then ; Value: ReferenceError: Can't find variable: SSSnackbar file:///app/tns_modules/nativescript-snackbar/snackbar.js:13:45
	ZoneAwarePromise@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:465:37
	simple@file:///app/tns_modules/nativescript-snackbar/snackbar.js:10:27
	showSimple@file:///app/app-components/map/map.component.js:203:30

I am using: COCOAPODS: 1.1.1:

PODS:
  - SSSnackbar (0.1.2)
DEPENDENCIES:
  - SSSnackbar
SPEC CHECKSUMS:
  SSSnackbar: 6a16cf8ab848d99a03ba21a7dab94d4478beabed

**Comment by bradmartin** [comment]
I've seen someone report an error with angular nativescript before and they linked to zone.js and I believe @hdeshev on the core team said zone.js sometimes masks the actual errors. My angular2 knowledge is very limited. Does this look familiar to either of you @triniwiz @roblav96 ?

**Comment by bradmartin** [comment]
@marcbuils - I noticed on the issue #14 you had angular deps. Could you provide me a working sample here and possibly a PR with any extra config needed for angular on the README.

**Comment by marcbuils** [comment]
@bradmartin I use the plugin without extra config.
The following example is the light version of an Angular service with Snackbar :
https://gist.github.com/marcbuils/80324d1ab4447b3ebc0df98c1c8c1fc5

**Comment by marcbuils** [comment]
@greenstevester: For information, my project works with the same version of SSSnackbar that you :
- COCOAPODS: 1.1.1
- SSSnackbar (0.1.2)
 => SSSnackbar: 6a16cf8ab848d99a03ba21a7dab94d4478beabed

I use nativescript-snackbar v1.1.5

**Comment by bradmartin** [comment]
Thanks @marcbuils - I didn't think there was any extra config to make it work, just wanted to be certain. I'm closing this for now. @magar91 if you have any errors when trying to use it let's open a new issue with the specific error to keep. Thanks 😄

**Comment by magar91** [comment]
thanks for the help I'll write back if any error shows up

**Comment by greenstevester** [comment]
@marcbuils, @bradmartin - thanks also for your help and suggestions - strangely enough, I got it working after I cloned https://github.com/stonesam92/SSSnackbar ,  installed in Xcode, then cleaned and rebuilt my project.

**Comment by echosalik** [comment]
**Never mind:** Cleaning the platforms' directory made it work. Thanks!
@bradmartin Hi, I get this error:
JS: StaticInjectorError(Platform: core)[DashComponent -> SnackBar]:
JS:     NullInjectorError: No provider for SnackBar!
If I add it in provders, the code works but I dont get a snackbar. Any ideas? Im using android BTW.

PS: How do you add a multiline code block?
