### ISSUE TITLE
{N} v-2.4.2 pod v-1.1.1  iOS - Unable to find a specification for `SSSnackbar`

### ISSUE THREAD

**Issue by upender-devulapally** [bradmartin/nativescript-snackbar#17]
Hi,
Below are the versions I am currently using
**NativeScript - 2.4.2 with angular 2**
added nativescript-snackbar plugin to package.json (via tns plugin add nativescript-snackbar)
`"nativescript-snackbar": "^1.1.6"`
removed and added platform after plugin installed
`tns platform remove ios
`
`
  tns platfrom add ios
`
when I run the 
**_` tns prepare ios`_**

getting below error(all other plugins and pods installed successfully like toast pod ,except this one)

Found peer TypeScript 2.0.10
Successfully prepared plugin nativescript-angular for ios.
Successfully prepared plugin nativescript-intl for ios.
Successfully prepared plugin nativescript-cardview for ios.
Successfully prepared plugin nativescript-effects for ios.
Successfully prepared plugin nativescript-imagepicker for ios.
Successfully prepared plugin nativescript-telerik-ui for ios.
Successfully prepared plugin tns-core-modules for ios.
Successfully prepared plugin tns-core-modules-widgets for ios.
Successfully prepared plugin nativescript-iqkeyboardmanager for ios.
nativescript-permissions is not supported for ios.
Successfully prepared plugin nativescript-permissions for ios.
Successfully prepared plugin nativescript-photoviewer for ios.
Successfully prepared plugin nativescript-pulltorefresh for ios.
Successfully prepared plugin nativescript-snackbar for ios.
Successfully prepared plugin nativescript-toasts for ios.
Installing pods...
Analyzing dependencies
[!] Unable to find a specification for `SSSnackbar`
Processing node_modules failed. Error: Command pod failed with exit code 1

**when I remove the plugin and below is the o/p of** 
`tns prepare ios`
Successfully prepared plugin nativescript-pulltorefresh for ios.
Successfully prepared plugin nativescript-toasts for ios.
Installing pods...
Analyzing dependencies
Downloading dependencies
Installing FLAnimatedImage (1.0.12)
Installing IQKeyboardManager (4.0.8)
Installing NYTPhotoViewer (1.1.0)
Installing Toast (3.1.0)
Generating Pods project
Integrating client project

**_is there anything I am missing here(I am not familier with iOS development )?_**

**Comment by bradmartin** [comment]
Might be issue with your cocoa pod version locally. What version do you
have installed? I use 0.39 and have no issues. Many bugs with pods 1.0 if
you have it.

**Comment by upender-devulapally** [comment]
Hi @bradmartin thank you very much for your quick reply,
My cocoa pod version is 1.1.1 
but other plugins like 
nativescript-toasts' i.e pod 'Toast' and 
nativescript-iqkeyboardmanager i.e pod 'IQKeyboardManager' are
by default(when run the app) working fine with {N} without changing any Pod files I mean platform specific changes.

**Comment by upender-devulapally** [comment]
@bradmartin  let me try for your current version of cocoa pod by downgrading in my OS and will try

**Comment by bradmartin** [comment]
Pod issues are no fun :( I've never had any issues with it which of course
makes it hard to figure out. Keep me posted on what you find out

**Comment by bradmartin** [comment]
Just tested this in an app and all worked fine. Just make sure you run `tns plugin add nativescript-snackbar`, uninstall any old builds of the app on device/simulators, run `tns build ios` and last `tns livesync ios --watch` or `tns run ios`. That is the approach I take everytime I add a plugin and it's very rare I encounter issues. I'm running cocoapods 1.1.1 now also with latest NativeScript. So it's likely an issue that the plugin source isn't in the executable you are running on the device/simulator. Which uninstalling, new build, then running should fix. Hope this helps some 😄

**Comment by upender-devulapally** [comment]
Hi @bradmartin ,
Followed the way you mentioned  but still no luck, below is o/p,
<img width="662" alt="screen shot 2017-01-26 at 11 39 49 am" src="https://cloud.githubusercontent.com/assets/1518942/22321662/9f7fb93a-e3bc-11e6-8a76-0d5af914c222.png">

and tried by removing platform and adding , and rebuild and removing node_modules and installing them I mean all the cases..

**Comment by upender-devulapally** [comment]
For android  I followed the article wrote by you and working fine  without plugin;
https://bradmartin.net/2015/12/08/how-to-use-material-design-snackbar-in-a-nativescript-app/
But I want it to be work in iOS also .. So I am looking for that.

**Comment by bradmartin** [comment]
Understand, I tested on iOS and it works fine for me. Something is wrong with your project I'm assuming, hard to say since there are many moving pieces here :/

**Comment by rijine** [comment]
Same problem for me...
[!] Unable to find a specification for `SSSnackbar`
Processing node_modules failed. Error: Command pod failed with exit code 1 Error output:

**Comment by rijine** [comment]
Looks like '**pod repo update**' solved the problem.
