### ISSUE TITLE
iOS - displays just a single line

### ISSUE THREAD

**Issue by erjdriver** [bradmartin/nativescript-snackbar#19]
On iOS - displays just a single line. Anyway that could be made unlimited or at least a 2-3 lines.

Messages have to be very short or get truncated.

Thanks.

**Comment by bradmartin** [comment]
Nothing that can be supported unless we get rid of the cocoapod dependency for iOS or fork and update it for this use case. A snackbar is supposed to be used for small info messages (just a guideline 😄 ) but I think Android will do the same after a certain character amount. 

I have no experience with Obj-C or Swift so I don't know how you'd go about doing this and I don't have the time to dedicate to learn it right now. If you're familiar with iOS and want to fork the pod and add this behavior (or maybe suggest it on the original pod repo and the author might add the functionality then we don't have to do anything but update the version here).

Hope that helps some, sorry it's not what you were looking for probably.

**Comment by erjdriver** [comment]
I'm not trying to display a lot - maybe 8-10 words.

It's a pity - but I understand.

No worries - I'll just pop up alerts.
