### ISSUE TITLE
d: framework not found SSSnackbar

### ISSUE THREAD

**Issue by davidmontgom** [bradmartin/nativescript-snackbar#20]
Why?? I removed the plugin and all references of the the code since I am using iOS.

Why will your code not go away when I try and build in xcode?

ld: warning: directory not found for option '-F/Users/Library/Developer/Xcode/DerivedData/MindfullTimer-bhozrumjomfxubadqoduapdwitel/Build/Products/Debug-iphonesimulator/SSSnackbar'
ld: framework not found SSSnackbar
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bradmartin** [comment]
Have you cleaned the platform directory, or just deleted and added it back? Once you add native code to the project it ends up in the platforms folder which contains the native application that gets built. So you can do a few things to remove it from the built application. Remove and add the platform iOS. Or use the cli tns plugin remove cmd, and then make sure you uninstall any installed builds from a device or simulator, and last run a new build to ensure the plugin and it's references are no longer in the built application. Hope that helps. If that doesn't work then it would help to know the cmds you executed to add the plugin and how you built the app. I've seen some instances where something messes up during a build step but the steps above should work. Please let me know the result.
