### ISSUE TITLE
Does not work on a case sensitive file sytem

### ISSUE THREAD

**Issue by simonox** [bradmartin/nativescript-snackbar#22]
Platform: iOS
Error: Pod is not installed. This will cause a runtime exception on first "usage". 
Version: 1.1.6

```
Error: Uncaught (in promise): ReferenceError: Can't find variable: SSSnackbar
```

Pod is not installed on a case sensitive file system. NativeScript is looking for a file named ```Podfile```. The file is named ```PodFile```. So it is ignored if your file system is case sensitive.

See also: https://github.com/bradmartin/nativescript-floatingactionbutton/issues/56

**Comment by bradmartin** [comment]
1.1.7 published with fix, thanks 👍
