### ISSUE TITLE
Set the background and text color for a simple notification

### ISSUE THREAD

**Issue by cgebe** [bradmartin/nativescript-snackbar#25]
I want to set the background and  text color for the `simple` notification. However i can't call `simple` with `options`. Removing the close button from a notification called with `action` is not possible either.
Is there a way to achieve this in the current version?

**Comment by bradmartin** [comment]
This should work with 1.3.0 just published. Just added two new args to the `simple` method that are optional to set the text and background color.

**Comment by cgebe** [comment]
Thank you very much!
