### ISSUE TITLE
Wrap Text in snackbar

### ISSUE THREAD

**Issue by gonick** [bradmartin/nativescript-snackbar#33]
Any possibility to wrap text to next line in snackbar?
![img_9456](https://user-images.githubusercontent.com/29632821/44622469-928d4680-a8d6-11e8-8704-665dc607ea3d.PNG)

**Comment by bradmartin** [comment]
Looks like it might be possible by modifying the textview 👍 https://stackoverflow.com/a/31429069/1893557

**Comment by bradmartin** [comment]
Try out v3.2.0 👍 - README has doc updated
